import type { Metadata } from "next";
import { Kanit } from 'next/font/google';

import "./globals.css";
import Profile from "./components/profile";

const kanit = Kanit({
  subsets: ["thai", "latin"],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Kilakorn Ongkhachuen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={kanit.className}>
      <body className="flex flex-col lg:flex-row items-start justify-center gap-5 mt-10 px-4 sm:px-10 lg:px-40 bg-black">
        <Profile />
        <main className="flex-1 w-full">{children}</main>
      </body>
    </html>
  );
}
